version: '3.8'

services:
  ai-purwa:
    container_name: ai-purwa-image-detection
    build: .
    ports:
      - "8501:8501"
    # env_file:
    #   - .env
    # volumes:
    #   - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
